### ISSUE TITLE
GNSS parsing field keywords (and altitude)

### ISSUE THREAD

**Issue by bsimmo** [ConnectedHumber/MQTT#1]
Could we add "lon" as an alternative to "long"
I assume we may want to add "longitude" and "latitude" too.
I've always used lon  as in lon/lat coordinates.

(as a side github uses a terrible font as you cannot distinguish between I and l )
Poor choice of screen font from them.

In my opinion "alt" "altitude" would also be good, I send "alt" but I know we're not capable yet of using it.
I future it may give an indication if up the hill is better than down the valley.

(this is purely a GPS thing, not an above ground measurement)

**Comment by bsimmo** [comment]
A quick check on TTN and GPS logger uses both full names and lon/lat/alt
https://github.com/ttn-be/ttnmapper/blob/master/ttnmapper.py
I assume that's also a TTN method?

That and we should be calling GPS with the term GNSS. GPS is just one satellite system ;-)

I notice they also want some method of GNSS accuracy.

**Comment by BNNorman** [comment]
No problem with lat/lon - we have an 'alias' dictionary. I'll add them to it. Later today.

**Comment by BNNorman** [comment]
Adding altitude/alt would required adding a field to the database

**Comment by bsimmo** [comment]
I noticed the alias list, hence I asked :-)

I guess over time many things may get added, different VOC's will be another.
windspeed, direction, waterfall.... UV

**Comment by BNNorman** [comment]
I'm working on this

```
# GPS position keys
GPS_Aliases={}
GPS_Aliases["lon"]="longitude"
GPS_Aliases["long"]="longitude"
GPS_Aliases["longitude"]="longitude"
GPS_Aliases["lat"]="lattitude"
GPS_Aliases["altitude"]="altitude"	# currently not stored
GPS_Aliases["alt"]="altitude"
```


```
####################################
#
# getLatLonAlt()
#
# returns tuple (lat,lon,alt)
def getLatLonAlt():
	global GPS_Aliases

	latitude=None
	longitude=None
	altitude=None

	for k in GPS_Aliases.keys():
		if k in payloadJson:
			if GPS_Aliases[k]=="longitude":
				longitude=payloadJson[k]
			elif GPS_Aliases[k]=="latitude":
				latitude=payloadJson[k]
			elif GPS_Aliases[K]=="altitude":
				altitude=payloadJson[k]

	return(latitude,longitude,altitude)

```
It really does complicate the SQL string selection. But hey ho.

Yes, I'm sure all that lovely stuff that should have been thought of at the beginning will come back to bite us.

I will run this past Robin and test it before updating Github.

**Comment by bsimmo** [comment]
other than a few typo and you shouldn't need _global GPS_Aliases_ (you are only reading it, not writing to it)
corrected it for you

```

# GPS position keys
GPS_Aliases={}
GPS_Aliases["lon"]="longitude"
GPS_Aliases["long"]="longitude"
GPS_Aliases["longitude"]="longitude"
GPS_Aliases["lat"]="latitude"
GPS_Aliases["latitude"]="latitude"
GPS_Aliases["altitude"]="altitude"  # currently not stored
GPS_Aliases["alt"]="altitude"

payload = {"dev":"brian04","PM25":61.30,"PM10":125.10,"lat":54.5356,"lon":-0.45988,"alt":34}
####################################
#
# getLatLonAlt()
#
# returns tuple (lat,lon,alt)
def getLatLonAlt(payloadJson):

    latitude=None
    longitude=None
    altitude=None

    for k in GPS_Aliases.keys():
        if k in payloadJson:
            if GPS_Aliases[k]=="longitude":
                longitude=payloadJson[k]
            elif GPS_Aliases[k]=="latitude":
                latitude=payloadJson[k]
            elif GPS_Aliases[k]=="altitude":
                altitude=payloadJson[k]

    return(latitude,longitude,altitude)

location = getLatLonAlt(payload)
print(location)
```

**Comment by BNNorman** [comment]
Thanks Ben - I hadn't finished getting rid of the warts - had to dash to join my octogenarian Mum for lunch. Input appreciated.

I tend to use 'global' to make sure python doesn't make an assumption that something is local - belt and braces - also reminds me when reading the code.

**Comment by BNNorman** [comment]
Update - just waiting to see if any other device columns need adding at the same time e.g. height above ground. This will be discussed at the meeting on Friday 1st March at C4DI. To make the new device columns functional will require a new release of the dbLoader program so there will be some testing to do before it can go live.

**Comment by BNNorman** [comment]
There were a number of changes in June which resulted in changes to the devices table and the addition of two extra tables sensors and device_sensor. 

The device_types table still needs some thought since, although many devices are of the same 'type' parts of their spec can change and hence the type also changes. Currently I am adding a new type for each new device even if it is a duplicate - that allows changes to be made that don't affect other devices.
