### ISSUE TITLE
Rogue Data Needs Removing

### ISSUE THREAD

**Issue by BNNorman** [ConnectedHumber/MQTT#3]
Please add any rogue data you need **removing** by commenting on this issue. 

Removing the rogue data will help the Air Quality Map device displays to be correct.

The information we require is : device_name (e.g. brian01) and data types to remove (PM, Humidity, Temperature, Pressure)

This issue will be closed when the work has been completed.

**Comment by BNNorman** [comment]
Pls remove the following:-

brian01: PM values
brian02,brian03,brian04:humidity,pressure and temperature

**Comment by adamjennison** [comment]
Adam01

Pressure readings: delete any reading above 1058 - same can be said for anyone's readings as that's the highest recorded in northern Europe.
There's some of mine around Jan 23rd that touch 10,000

😲

**Comment by adamjennison** [comment]
On Adam01 again..
Nov 28th pressure readings, there's a number really low, around 913.. these should be deleted, anything under 960 are false readings.
👍

**Comment by BNNorman** [comment]
10,000 I can agree with. 913 I don't. I found a site where this comment was made.

"Adding a bme.readTemperature() statement to the program prior to my bme.readPressure() statement made a world of difference. I'm now getting correlation between the BME280 readings and local pressure data to around 0.1% ."

Are you doing this? (I am using ESP Easy so will read the code)

**Comment by BNNorman** [comment]
Removed all the rogue data I was informed about
